// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (title, model)
VALUES (?, ?)
RETURNING id, title, model, created_at, updated_at
`

type CreateConversationParams struct {
	Title string `json:"title"`
	Model string `json:"model"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.Title, arg.Model)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, title, model, created_at, updated_at FROM conversations
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, title, model, created_at, updated_at FROM conversations
ORDER BY updated_at DESC
LIMIT ?
`

func (q *Queries) ListConversations(ctx context.Context, limit int64) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TouchConversation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchConversation, id)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE conversations
SET title = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateConversationTitleParams struct {
	Title string `json:"title"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationTitle, arg.Title, arg.ID)
	return err
}
