// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package sqlc

import (
	"context"
)

const getGoals = `-- name: GetGoals :one
SELECT id, kcal, protein_g, carbs_g, fat_g, created_at, updated_at FROM goals ORDER BY id LIMIT 1
`

func (q *Queries) GetGoals(ctx context.Context) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoals)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Kcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setGoals = `-- name: SetGoals :one
UPDATE goals SET
    kcal       = ?,
    protein_g  = ?,
    carbs_g    = ?,
    fat_g      = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = (SELECT id FROM goals ORDER BY id LIMIT 1)
RETURNING id, kcal, protein_g, carbs_g, fat_g, created_at, updated_at
`

type SetGoalsParams struct {
	Kcal     *float64 `json:"kcal"`
	ProteinG *float64 `json:"protein_g"`
	CarbsG   *float64 `json:"carbs_g"`
	FatG     *float64 `json:"fat_g"`
}

func (q *Queries) SetGoals(ctx context.Context, arg SetGoalsParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, setGoals,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Kcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
