// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package sqlc

import (
	"context"
	"time"
)

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals WHERE id = ?
`

func (q *Queries) DeleteMeal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMeal, id)
	return err
}

const getMeal = `-- name: GetMeal :one
SELECT id, title, description, items, kcal, protein_g, carbs_g, fat_g, eaten_at, created_at FROM meals WHERE id = ? LIMIT 1
`

func (q *Queries) GetMeal(ctx context.Context, id int64) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMeal, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Items,
		&i.Kcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.EatenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMealsBetween = `-- name: ListMealsBetween :many
SELECT id, title, description, items, kcal, protein_g, carbs_g, fat_g, eaten_at, created_at FROM meals
WHERE eaten_at >= ? AND eaten_at < ?
ORDER BY eaten_at ASC
`

type ListMealsBetweenParams struct {
	EatenAt   time.Time `json:"eaten_at"`
	EatenAt_2 time.Time `json:"eaten_at_2"`
}

func (q *Queries) ListMealsBetween(ctx context.Context, arg ListMealsBetweenParams) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listMealsBetween, arg.EatenAt, arg.EatenAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Items,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.EatenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMeals = `-- name: ListRecentMeals :many
SELECT id, title, description, items, kcal, protein_g, carbs_g, fat_g, eaten_at, created_at FROM meals
ORDER BY eaten_at DESC
LIMIT ?
`

func (q *Queries) ListRecentMeals(ctx context.Context, limit int64) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMeals, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Items,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.EatenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveMeal = `-- name: SaveMeal :one
INSERT INTO meals (title, description, items, kcal, protein_g, carbs_g, fat_g, eaten_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, description, items, kcal, protein_g, carbs_g, fat_g, eaten_at, created_at
`

type SaveMealParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Items       string    `json:"items"`
	Kcal        float64   `json:"kcal"`
	ProteinG    float64   `json:"protein_g"`
	CarbsG      float64   `json:"carbs_g"`
	FatG        float64   `json:"fat_g"`
	EatenAt     time.Time `json:"eaten_at"`
}

func (q *Queries) SaveMeal(ctx context.Context, arg SaveMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, saveMeal,
		arg.Title,
		arg.Description,
		arg.Items,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.EatenAt,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Items,
		&i.Kcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.EatenAt,
		&i.CreatedAt,
	)
	return i, err
}
