// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO messages (conversation_id, role, content)
VALUES (?, ?, ?)
RETURNING id, conversation_id, role, content, created_at
`

type AppendMessageParams struct {
	ConversationID int64  `json:"conversation_id"`
	Role           string `json:"role"`
	Content        string `json:"content"`
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, appendMessage, arg.ConversationID, arg.Role, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM messages
WHERE conversation_id = ?
`

func (q *Queries) CountMessages(ctx context.Context, conversationID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, created_at FROM messages
WHERE conversation_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMessages(ctx context.Context, conversationID int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
