// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package sqlc

import (
	"context"
)

const deletePreference = `-- name: DeletePreference :exec
DELETE FROM preferences WHERE key = ?
`

func (q *Queries) DeletePreference(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deletePreference, key)
	return err
}

const getPreference = `-- name: GetPreference :one
SELECT value FROM preferences WHERE key = ?
`

func (q *Queries) GetPreference(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPreference, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setPreference = `-- name: SetPreference :exec
INSERT INTO preferences (key, value)
VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET
    value      = excluded.value,
    updated_at = CURRENT_TIMESTAMP
`

type SetPreferenceParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetPreference(ctx context.Context, arg SetPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, setPreference, arg.Key, arg.Value)
	return err
}
