// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error)
	CountMessages(ctx context.Context, conversationID int64) (int64, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	DeleteConversation(ctx context.Context, id int64) error
	DeleteMeal(ctx context.Context, id int64) error
	DeletePreference(ctx context.Context, key string) error
	GetConversation(ctx context.Context, id int64) (Conversation, error)
	GetGoals(ctx context.Context) (Goal, error)
	GetMeal(ctx context.Context, id int64) (Meal, error)
	GetPreference(ctx context.Context, key string) (string, error)
	ListConversations(ctx context.Context, limit int64) ([]Conversation, error)
	ListMealsBetween(ctx context.Context, arg ListMealsBetweenParams) ([]Meal, error)
	ListMessages(ctx context.Context, conversationID int64) ([]Message, error)
	ListRecentMeals(ctx context.Context, limit int64) ([]Meal, error)
	SaveMeal(ctx context.Context, arg SaveMealParams) (Meal, error)
	SetGoals(ctx context.Context, arg SetGoalsParams) (Goal, error)
	SetPreference(ctx context.Context, arg SetPreferenceParams) error
	TouchConversation(ctx context.Context, id int64) error
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error
}

var _ Querier = (*Queries)(nil)
